### ISSUE TITLE
Argument to subroutine not indexed

### ISSUE THREAD

**Issue by aoloso** [claw-project/claw-compiler#578]
Description of the issue in few words.
Please take a look at the line "call set_p(...)" in the original code, transformed code, and expected correctly transformed code as included below. Array 'p' is not being properly indexed in the transformed code.   
**Original code**
```fortran
! Original code before transformation
module test_index_mod
   implicit none
contains

   subroutine top_p(vert, p)
      integer, intent(in) :: vert
      real, intent(out):: p(vert)

      !$claw define dimension i(1:IM) &
      !$claw define dimension j(1:JM) &
      !$claw sca data(p) over(i,j,:)

      !$claw sca forward
      call set_p(vert, p)

   end


   subroutine set_p(vert, p)
      integer, intent(in) :: vert
      real, intent(out):: p(vert)

      integer :: k

      !$claw sca routine
      do k = 1, vert
         p(k) = 1.0
      enddo
   end

end module test_index_mod
! Can also be XcodeML directly
```

**Transformation code**
```fortran
! Wrong code after being processed by CLAW
MODULE test_index_mod

CONTAINS
 SUBROUTINE top_p ( vert , p , im , jm )
  INTEGER , INTENT(IN) :: jm
  INTEGER , INTENT(IN) :: im

  INTEGER , INTENT(IN) :: vert
  REAL , INTENT(OUT) :: p ( 1 : im , 1 : jm , 1 : vert )
  INTEGER :: i
  INTEGER :: j

!$acc data present(p)
!$acc parallel
!$acc loop gang vector collapse(2)
  DO j = 1 , jm , 1
   DO i = 1 , im , 1
    CALL set_p ( vert , p )
   END DO
  END DO
!$acc end parallel
!$acc end data
 END SUBROUTINE top_p

 SUBROUTINE set_p ( vert , p )

  INTEGER , INTENT(IN) :: vert
  REAL , INTENT(OUT) :: p ( 1 : vert )
  INTEGER :: k

!$acc routine seq
  DO k = 1 , vert , 1
   p ( k ) = 1.0
  END DO
 END SUBROUTINE set_p

END MODULE test_index_mod
! Can also be XcodeML directly
```

**Expected code**
```fortran
! Expected code
MODULE test_index_mod

CONTAINS
 SUBROUTINE top_p ( vert , p , im , jm )
  INTEGER , INTENT(IN) :: jm
  INTEGER , INTENT(IN) :: im

  INTEGER , INTENT(IN) :: vert
  REAL , INTENT(OUT) :: p ( 1 : im , 1 : jm , 1 : vert )
  INTEGER :: i
  INTEGER :: j

!$acc data present(p)
!$acc parallel
!$acc loop gang vector collapse(2)
  DO j = 1 , jm , 1
   DO i = 1 , im , 1
    CALL set_p ( vert , p( i, j, 1:pvert )
   END DO
  END DO
!$acc end parallel
!$acc end data
 END SUBROUTINE top_p

 SUBROUTINE set_p ( vert , p )

  INTEGER , INTENT(IN) :: vert
  REAL , INTENT(OUT) :: p ( 1 : vert )
  INTEGER :: k

!$acc routine seq
  DO k = 1 , vert , 1
   p ( k ) = 1.0
  END DO
 END SUBROUTINE set_p

END MODULE test_index_mod
! Can also be XcodeML directly
```

**Execution of `clawfc`**
```bash
# Command used to apply the transformation
```
 clawfc --directive=openacc --target=gpu -o test_index_acc.f90 test_index.f90
## Related issues (if any)
Issue #00

**Comment by clementval** [comment]
If the subroutine has claw sca routine, then the call should not be decorated with sca forward. This will not do anything since no promotion or other transformation happened in set_p

On Nov 5, 2019, at 15:20, Amidu Oloso <notifications@github.com> wrote:

﻿

Description of the issue in few words.
Please take a look at the line "call set_p(...)" in the original code, transformed code, and expected correctly transformed code as included below. Array 'p' is not being properly indexed in the transformed code.
Original code

! Original code before transformation
module test_index_mod
   implicit none
contains

   subroutine top_p(vert, p)
      integer, intent(in) :: vert
      real, intent(out):: p(vert)

      !$claw define dimension i(1:IM) &
      !$claw define dimension j(1:JM) &
      !$claw sca data(p) over(i,j,:)

      !$claw sca forward
      call set_p(vert, p)

   end


   subroutine set_p(vert, p)
      integer, intent(in) :: vert
      real, intent(out):: p(vert)

      integer :: k

      !$claw sca routine
      do k = 1, vert
         p(k) = 1.0
      enddo
   end

end module test_index_mod
! Can also be XcodeML directly

Transformation code

! Wrong code after being processed by CLAW
MODULE test_index_mod

CONTAINS
 SUBROUTINE top_p ( vert , p , im , jm )
  INTEGER , INTENT(IN) :: jm
  INTEGER , INTENT(IN) :: im

  INTEGER , INTENT(IN) :: vert
  REAL , INTENT(OUT) :: p ( 1 : im , 1 : jm , 1 : vert )
  INTEGER :: i
  INTEGER :: j

!$acc data present(p)
!$acc parallel
!$acc loop gang vector collapse(2)
  DO j = 1 , jm , 1
   DO i = 1 , im , 1
    CALL set_p ( vert , p )
   END DO
  END DO
!$acc end parallel
!$acc end data
 END SUBROUTINE top_p

 SUBROUTINE set_p ( vert , p )

  INTEGER , INTENT(IN) :: vert
  REAL , INTENT(OUT) :: p ( 1 : vert )
  INTEGER :: k

!$acc routine seq
  DO k = 1 , vert , 1
   p ( k ) = 1.0
  END DO
 END SUBROUTINE set_p

END MODULE test_index_mod
! Can also be XcodeML directly

Expected code

! Expected code
MODULE test_index_mod

CONTAINS
 SUBROUTINE top_p ( vert , p , im , jm )
  INTEGER , INTENT(IN) :: jm
  INTEGER , INTENT(IN) :: im

  INTEGER , INTENT(IN) :: vert
  REAL , INTENT(OUT) :: p ( 1 : im , 1 : jm , 1 : vert )
  INTEGER :: i
  INTEGER :: j

!$acc data present(p)
!$acc parallel
!$acc loop gang vector collapse(2)
  DO j = 1 , jm , 1
   DO i = 1 , im , 1
    CALL set_p ( vert , p( i, j, 1:pvert )
   END DO
  END DO
!$acc end parallel
!$acc end data
 END SUBROUTINE top_p

 SUBROUTINE set_p ( vert , p )

  INTEGER , INTENT(IN) :: vert
  REAL , INTENT(OUT) :: p ( 1 : vert )
  INTEGER :: k

!$acc routine seq
  DO k = 1 , vert , 1
   p ( k ) = 1.0
  END DO
 END SUBROUTINE set_p

END MODULE test_index_mod
! Can also be XcodeML directly

Execution of clawfc

# Command used to apply the transformation

clawfc --directive=openacc --target=gpu -o test_index_acc.f90 test_index.f90

Related issues (if any)

Issue #00

**Comment by aoloso** [comment]
Removing sea forward and rerunning clawfc makes no difference. Also removing sea routine makes no difference. Removing both makes no difference. I do get the warning message:

test_index.f90:14:- warning: set_p has not been found. Automatic routine directive generation could not be done.

**Comment by aoloso** [comment]
Of course "sea" should be "sca"

**Comment by clementval** [comment]
Ok I see what you mean now. I have to check what is happening in the code but you might have found a bug.

**Comment by clementval** [comment]
This is a bug since p is not correctly detected as an array in the call to `set_p`. As a work around you can pass `p` as `(:)` and it works correctly.

```
! Original code before transformation
module test_index_mod
   implicit none
contains

   subroutine top_p(vert, p)
      integer, intent(in) :: vert
      real, intent(out):: p(vert)

      !$claw define dimension i(1:IM) &
      !$claw define dimension j(1:JM) &
      !$claw sca data(p) over(i,j,:)

      !$claw sca forward
      call set_p(vert, p)

   end


   subroutine set_p(vert, p)
      integer, intent(in) :: vert
      real, intent(out):: p(vert)

      integer :: k

      !$claw sca routine
      do k = 1, vert
         p(k) = 1.0
      enddo
   end

end module test_index_mod
! Can also be XcodeML directly
```
